Rewiev
PolPav/Mindk-Shop pull request #1
Opened 2016-10-02 06:36 UTC by PolPav

2016-10-02 07:11 UTC, Artiomtb requested changes
Рефактор кода, code-style, phpdocs, переделать workflow.

2016-10-02 07:11 UTC, Artiomtb commented on app/Catalog.php
> +        ob_start();
Убрать

2016-10-02 07:11 UTC, Artiomtb commented on app/Category.php
> +        ob_start();
Не нужно.

2016-10-02 07:11 UTC, Artiomtb commented on app/Category.php
> +
Везде писать доки к методам

2016-10-02 07:11 UTC, Artiomtb commented on app/config/routes.php
>      ['pattern' => '',
Почему не сделать как /?

2016-10-02 07:11 UTC, Artiomtb commented on public/index.php
> +/**
Такого комитить не надо.

2016-10-02 07:11 UTC, Artiomtb commented on vendor/framework/App.php
> +use polpav\framework\response\Response;
Все namespaces писать с большой буквы (PSR-4)

2016-10-02 07:11 UTC, Artiomtb commented on vendor/framework/App.php
> +    /** function send headers and content,
Всё это не нужно хранить в App. Это логика Response

2016-10-02 07:11 UTC, Artiomtb commented on vendor/framework/App.php
> +    public function render(){
?

2016-10-02 07:11 UTC, Artiomtb commented on vendor/framework/Request.php
> +        if ($_SERVER['REQUEST_METHOD'] == 'GET' && $key == null){
Подумай, как это можно отрефакторить

2016-10-02 07:11 UTC, Artiomtb commented on vendor/framework/response/Response.php
> +        if($request_header['Content-Type'] == 'application/json'){
Для чего?

2016-10-02 16:59 UTC, ddavidov reviewed
Если где-то открываешь ob_start() то нужно же его потом и закрывать... В адаптере попробуй предусмотреть возм. упаковки результата выборки в объект(ы) заданного класса.
Продолжай :)

2016-10-02 16:59 UTC, ddavidov commented on app/config/routes.php
>      ['pattern' => '',
Артём имел в виду `['pattern' => '/'` ...

2016-10-02 16:59 UTC, ddavidov commented on vendor/framework/App.php
> +use polpav\framework\response\Response;
++

2016-10-02 16:59 UTC, ddavidov commented on vendor/framework/App.php
> +    /** function send headers and content,
Я бы даже вынес как отдельный файл типа globalfunc.php и включал его инклудом тупо в файле index.php/
туда же можно потом включить и view(...) и trans(...) и прочее.

2016-10-02 16:59 UTC, ddavidov commented on vendor/framework/Router.php
> +        $this->routing_map[] = $build;
Тут скорее имелось в виду, что нам нужна ф-ция построения ссылки. Например, нам нужно сгенерить линк на 141й товар, тогда, мы вызываем некий метод роутера:
`...
$router->buildRoute('single_product', ['id' => 141]);
`
И он возвращает нам: http://shop.com/product/141 или просто /product/141
НО! на основе карты маршрутов.

2016-10-06 18:47 UTC, ddavidov requested changes
Просмотри новые каменты плз. Изменения - хорошо, гуд. И напимни мне при случае, о "queryBuild"

2016-10-06 18:47 UTC, ddavidov commented on public/index.php
> +$app->queryBuilder('/category','App\CategoryController','categoryAction', 'params');
Ыыыхх... напомни мне пожалуйста в среду, за этот "query Builder", я расскажу. Заодно всем.

2016-10-06 18:47 UTC, ddavidov commented on vendor/composer/autoload_static.php
>      );
В этот файл вмешиваться не желательно, работай с composer.json. При composer.update, это всё скорее всего затрётся

2016-10-06 18:47 UTC, ddavidov commented on vendor/framework/App.php
> +        $build->queryBuild($pattern, $class, $action, $params);
Будет сбивать с толку... Напомни всё же.

2016-10-06 18:47 UTC, ddavidov commented on vendor/framework/Request.php
> +        }
Тут можно было бы как-то оптимизировать )

2016-10-06 18:47 UTC, ddavidov commented on vendor/framework/Router.php
> +       public function queryBuild($pattern, $class, $action, $params)
Не, не тот замысел

2016-10-15 09:27 UTC, ddavidov approved these changes
Вижу, что потихоньку код нормализуется. Просмотри, пожалуйста, комментарии и можно сливать этот PullRequest в мастер ато мы запутаемся в нём потом.

2016-10-15 09:27 UTC, ddavidov commented on composer.json
> +      "PolPav\\": "vendor/framework"
Думаю, эту строчку надо бы в секцию повыше перенести (в "autoload")

2016-10-15 10:22 UTC, merged